// Code generated by goctl. DO NOT EDIT.
// Source: gateway.proto

package server

import (
	"im2/service/gateway/gateway"
	"im2/service/gateway/internal/logic"
	"im2/service/gateway/internal/svc"
)

type GatewayServer struct {
	svcCtx *svc.ServiceContext
	gateway.UnimplementedGatewayServer
}

func NewGatewayServer(svcCtx *svc.ServiceContext) *GatewayServer {
	return &GatewayServer{
		svcCtx: svcCtx,
	}
}
