// Code generated by goctl. DO NOT EDIT.
// Source: gateway.proto

package gatewayclient

import (
	"context"

	"im2/service/gateway/gateway"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AudioMessage       = gateway.AudioMessage
	CommandMessage     = gateway.CommandMessage
	ConnectRequest     = gateway.ConnectRequest
	ConnectResponse    = gateway.ConnectResponse
	DisconnectRequest  = gateway.DisconnectRequest
	DisconnectResponse = gateway.DisconnectResponse
	FileMessage        = gateway.FileMessage
	ImageMessage       = gateway.ImageMessage
	LocationMessage    = gateway.LocationMessage
	MarkdownMessage    = gateway.MarkdownMessage
	MergeMessage       = gateway.MergeMessage
	Message            = gateway.Message
	MessageContent     = gateway.MessageContent
	ReceiveRequest     = gateway.ReceiveRequest
	RichTextMessage    = gateway.RichTextMessage
	SendRequest        = gateway.SendRequest
	SendResponse       = gateway.SendResponse
	TextMessage        = gateway.TextMessage
	VideoMessage       = gateway.VideoMessage

	Gateway interface {
	}

	defaultGateway struct {
		cli zrpc.Client
	}
)

func NewGateway(cli zrpc.Client) Gateway {
	return &defaultGateway{
		cli: cli,
	}
}
