// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	login "im2/restful/user/internal/handler/login"
	user "im2/restful/user/internal/handler/user"
	"im2/restful/user/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// Login
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: login.LoginHandler(serverCtx),
			},
			{
				// Register a new user
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: login.RegisterHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// Get user list
				Method:  http.MethodGet,
				Path:    "/user",
				Handler: user.ListHandler(serverCtx),
			},
			{
				// Add a new user
				Method:  http.MethodPost,
				Path:    "/user",
				Handler: user.AddHandler(serverCtx),
			},
			{
				// Update user info
				Method:  http.MethodPut,
				Path:    "/user",
				Handler: user.UpdateHandler(serverCtx),
			},
			{
				// Update user info
				Method:  http.MethodPatch,
				Path:    "/user",
				Handler: user.PatchHandler(serverCtx),
			},
			{
				// Delete user
				Method:  http.MethodDelete,
				Path:    "/user",
				Handler: user.DeleteHandler(serverCtx),
			},
			{
				// Get user info
				Method:  http.MethodGet,
				Path:    "/user/:id",
				Handler: user.GetUserInfoHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)
}
