// Code generated by goctl. DO NOT EDIT.
package types

type AddFriendRequest struct {
	FriendId int64  `json:"friendId"`
	Remark   string `json:"remark"`
}

type AddFriendResponse struct {
	Success bool `json:"success"`
}

type AddGroupRequest struct {
	GroupId int64  `json:"groupId"`
	Name    string `json:"name"`
}

type AddGroupResponse struct {
	Success bool `json:"success"`
}

type AddUserRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Email    string `json:"email"`
}

type AddUserResponse struct {
	UserId int64 `json:"userId"`
}

type DeleteFriendRequest struct {
	FriendId int64 `json:"friendId"`
}

type DeleteGroupRequest struct {
	GroupId int64 `json:"groupId"`
}

type DeleteUserRequest struct {
	ID int64 `path:"id"`
}

type DeleteUserResponse struct {
	Success bool `json:"success"`
}

type FriendDeleteResponse struct {
	Success bool `json:"success"`
}

type FriendInfoResponse struct {
	FriendId int64  `json:"friendId"`
	Username string `json:"username"`
	Nickname string `json:"nickname"`
	Email    string `json:"email"`
	Avatar   string `json:"avatar"`
}

type FriendListRequest struct {
	UserId int64  `form:"userId,optional"`
	Page   int32  `form:"page,default=1"`
	Size   int32  `form:"size,default=10"`
	Search string `form:"search,optional"`
}

type FriendListResponse struct {
	Rows  []FriendInfoResponse `json:"rows"`
	Total int32                `json:"total"`
}

type GroupDeleteResponse struct {
	Success bool `json:"success"`
}

type GroupInfoResponse struct {
	GroupId int64  `json:"groupId"`
	Name    string `json:"name"`
}

type GroupListRequest struct {
	UserId int64 `form:"userId,optional"`
	Page   int32 `form:"page,default=1"`
	Size   int32 `form:"size,default=10"`
}

type GroupListResponse struct {
	Groups []GroupInfoResponse `json:"groups"`
}

type LoginRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResponse struct {
	UserId  int64  `json:"userId"`
	Token   string `json:"token"`
	Expire  int64  `json:"expire"`
	Refresh int64  `json:"refresh"`
}

type RegisterRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Email    string `json:"email"`
}

type RegisterResponse struct {
	Success bool `json:"success"`
}

type UpdateFriendRequest struct {
	FriendId int64 `json:"friendId"`
	Status   int32 `json:"status"`
}

type UpdateFriendResponse struct {
	Success bool `json:"success"`
}

type UpdateGroupRequest struct {
	GroupId int64  `json:"groupId"`
	Name    string `json:"name"`
}

type UpdateGroupResponse struct {
	Success bool `json:"success"`
}

type UpdateUserInfoRequest struct {
	UserId   int64  `json:"userId"`
	Email    string `json:"email,optional"`
	NickName string `json:"nickName,optional"`
	Avatar   string `json:"avatar,optional"`
	Status   int32  `json:"status,optional"`
}

type UpdateUserResponse struct {
	Success bool `json:"success"`
}

type UserInfoRequest struct {
	ID string `path:"id"`
}

type UserInfoResponse struct {
	UserId   int64  `json:"userId"`
	Username string `json:"username"`
	NickName string `json:"nickName"`
}

type UserListRequest struct {
	Page     int32  `form:"page,default=1"`
	Size     int32  `form:"size,default=10"`
	Username string `form:"username,optional"`
	NickName string `form:"nickName,optional"`
}

type UserListResponse struct {
	Rows  []UserInfoResponse `json:"users"`
	Total int32              `json:"total"`
}
