// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"

	"im2/service/user/internal/logic"
	"im2/service/user/internal/svc"
	"im2/service/user/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) Register(ctx context.Context, in *user.RegisterRequest) (*user.RegisterResponse, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *UserServer) Login(ctx context.Context, in *user.LoginRequest) (*user.LoginResponse, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *UserServer) GetInfo(ctx context.Context, in *user.GetInfoRequest) (*user.GetInfoResponse, error) {
	l := logic.NewGetInfoLogic(ctx, s.svcCtx)
	return l.GetInfo(in)
}

func (s *UserServer) UpdateInfo(ctx context.Context, in *user.UpdateInfoRequest) (*user.UpdateInfoResponse, error) {
	l := logic.NewUpdateInfoLogic(ctx, s.svcCtx)
	return l.UpdateInfo(in)
}

func (s *UserServer) DeleteInfo(ctx context.Context, in *user.DeleteInfoRequest) (*user.DeleteInfoResponse, error) {
	l := logic.NewDeleteInfoLogic(ctx, s.svcCtx)
	return l.DeleteInfo(in)
}

func (s *UserServer) GetList(ctx context.Context, in *user.GetListRequest) (*user.GetListResponse, error) {
	l := logic.NewGetListLogic(ctx, s.svcCtx)
	return l.GetList(in)
}
