// Code generated by goctl. DO NOT EDIT.
package types

type AddUserRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Email    string `json:"email"`
}

type DeleteUserRequest struct {
	UserId int64 `json:"userId"`
}

type LoginRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResponse struct {
	UserId int64  `json:"userId"`
	Token  string `json:"token"`
}

type RegisterRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Email    string `json:"email"`
}

type RegisterResponse struct {
	Success bool `json:"success"`
}

type UpdateUserInfoRequest struct {
	UserId   int64  `json:"userId"`
	Username string `json:"username,omitempty"`
	Email    string `json:"email,omitempty"`
}

type UserAddResponse struct {
	UserId int64 `json:"userId"`
}

type UserDeleteResponse struct {
	Success bool `json:"success"`
}

type UserInfoResponse struct {
	UserId   int64  `json:"userId"`
	Username string `json:"username"`
	NickName string `json:"nickName"`
}

type UserListResponse struct {
	Users []UserInfoResponse `json:"users"`
}

type UserUpdateResponse struct {
	Success bool `json:"success"`
}
