// Code generated by goctl. DO NOT EDIT.
// Source: groups.proto

package server

import (
	"context"

	"im2/service/groups/groups"
	"im2/service/groups/internal/logic"
	"im2/service/groups/internal/svc"
)

type GroupsServer struct {
	svcCtx *svc.ServiceContext
	groups.UnimplementedGroupsServer
}

func NewGroupsServer(svcCtx *svc.ServiceContext) *GroupsServer {
	return &GroupsServer{
		svcCtx: svcCtx,
	}
}

func (s *GroupsServer) CreateGroup(ctx context.Context, in *groups.CreateGroupRequest) (*groups.CreateGroupResponse, error) {
	l := logic.NewCreateGroupLogic(ctx, s.svcCtx)
	return l.CreateGroup(in)
}

func (s *GroupsServer) AddGroupMember(ctx context.Context, in *groups.AddGroupMemberRequest) (*groups.AddGroupMemberResponse, error) {
	l := logic.NewAddGroupMemberLogic(ctx, s.svcCtx)
	return l.AddGroupMember(in)
}

func (s *GroupsServer) RemoveGroupMember(ctx context.Context, in *groups.RemoveGroupMemberRequest) (*groups.RemoveGroupMemberResponse, error) {
	l := logic.NewRemoveGroupMemberLogic(ctx, s.svcCtx)
	return l.RemoveGroupMember(in)
}

func (s *GroupsServer) ListGroupMembers(ctx context.Context, in *groups.ListGroupMembersRequest) (*groups.ListGroupMembersResponse, error) {
	l := logic.NewListGroupMembersLogic(ctx, s.svcCtx)
	return l.ListGroupMembers(in)
}
